CREATE TABLE dbo.ExpenseOwner
(
	ExpenseOwnerId SMALLINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Expense_Owner_Id PRIMARY KEY CLUSTERED,
	OwnerUserId VARCHAR(255) NOT NULL,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL
)

GO
