version: '3.7'

services: 
  expensetrack.database:
    image:  sql.integration.database:v0.6
    container_name: sql.integration.database
    environment:
      - "ACCEPT_EULA=Y"
    ports:
      - "1944:1433"