version: '3.5'

services: 
  expensetrack.database:
    image:  dmaxim/mxinfo.expensetrack.database:v1.3
    container_name: mxinfo.expensetrack.database
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=0greVpRSqDfxgfoflI2c"
    ports:
      - "1944:1433"